CREATE DATABASE IF NOT EXISTS lakehouse;

CREATE TABLE IF NOT EXISTS lakehouse.behavioral_obt (
    event_key String,
    event_id Nullable(String),
    event_identity_source Nullable(String),
    event_timestamp DateTime64(3, 'Asia/Tehran'),
    date_key Int32,
    processing_date Date,
    user_key Nullable(String),
    user_id Nullable(String),
    session_key Nullable(String),
    session_id Nullable(String),
    session_start_at Nullable(DateTime64(3, 'Asia/Tehran')),
    session_end_at Nullable(DateTime64(3, 'Asia/Tehran')),
    session_duration_sec Nullable(Int64),
    session_event_count Nullable(Int64),
    device_key Nullable(String),
    device_name Nullable(String),
    primary_device_key Nullable(String),
    event_type_key Nullable(String),
    event_type Nullable(String),
    event_category Nullable(String),
    utm_source Nullable(String),
    ip_address_hash Nullable(String),
    product_id Nullable(String),
    order_id Nullable(String),
    url_path Nullable(String),
    query Nullable(String),
    wishlist_name Nullable(String),
    payment_type Nullable(String),
    shipping_method Nullable(String),
    fulfillment_speed Nullable(String),
    error_code Nullable(String),
    success Nullable(Bool),
    http_status Nullable(Int32),
    quantity Nullable(Int32),
    cart_total_items Nullable(Int32),
    cart_value Nullable(Float64),
    duration_sec Nullable(Int32),
    results_count Nullable(Int32),
    clicked_position Nullable(Int32),
    rating Nullable(Int32),
    text_length Nullable(Int32),
    cart_items_json Nullable(String),
    dq_flags_json Nullable(String),
    kafka_topic Nullable(String),
    kafka_partition Nullable(Int32),
    kafka_offset Nullable(Int64),
    kafka_timestamp Nullable(DateTime64(3, 'Asia/Tehran')),
    bronze_ingestion_timestamp Nullable(DateTime64(3, 'Asia/Tehran')),
    source_file Nullable(String),
    pipeline_run_id Nullable(String),
    silver_ingestion_timestamp DateTime64(3, 'Asia/Tehran'),
    gold_loaded_at DateTime64(3, 'Asia/Tehran')
)
ENGINE = ReplacingMergeTree(gold_loaded_at)
PARTITION BY processing_date
ORDER BY (
    processing_date,
    ifNull(event_category, ''),
    ifNull(event_type, ''),
    ifNull(user_key, ''),
    ifNull(session_key, ''),
    event_key
)
SETTINGS index_granularity = 8192;
